version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    steps:
      - checkout
      - node/with-cache:
        steps:
          - run: npm install
          - run: npm build
  deploy: 
    steps:
      - run: npm run deploy

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master