version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm build
  deploy: 
    executor:
      name: node/default
    steps:
      - run: npm run deploy
workflows:
  build-and-deploy:
    jobs:
      - build:
        name: build
      - deploy:
        name: deploy
        filters:
          branches:
            only:
              - master
        requires:
          - build